### ISSUE TITLE
newSharedContext should allow window configuration parameters to be passed in for the child context

### ISSUE THREAD

**Issue by duncanburke** [plredmond/GPipe-GLFW#10]
See [ Allow a shared context to take window parameters independent of its parent #19 ](https://github.com/tobbebex/GPipe-Core/issues/19)

**Comment by plredmond** [comment]
Thanks for the companion issue. I'm watching to see how things go with GPipe and will update accordingly. :)

**Comment by plredmond** [comment]
This is being added in the next version; there's a preview described here:
https://github.com/tobbebex/GPipe-Core/issues/36

**Comment by plredmond** [comment]
This is now in the released version. :)
http://hackage.haskell.org/package/GPipe-GLFW-1.4.0
