### ISSUE TITLE
Several instances of application

### ISSUE THREAD

**Issue by NCrashed** [plredmond/GPipe-GLFW#11]
Hi, @tobbebex assumes that the https://github.com/tobbebex/GPipe-Core/issues/20 problem is backend specific.

Could you tell me what exactly I am doing wrong ^^ ? Rendering loop: https://github.com/Teaspot-Studio/gore-and-ash/blob/master/testapp/src/client/Graphics.hs#L85

**Comment by NCrashed** [comment]
Ups, I fixed one network bug that was causing id conflict in arrow system and the bug has gone. Although I don't understand why the bug causes rendering to hang...

**Comment by NCrashed** [comment]
The real reason was the CPU starvation, server was using a lot of CPU so the second instance of client was starving. To fix that I implemented FPS boundary using [registerTimeout](http://haddock.stackage.org/lts-4.0/base-4.8.2.0/GHC-Event.html#v:registerTimeout) and MVar.

**Comment by plredmond** [comment]
Hey! Glad you found the issue. I didn't even get to your code yet. :)

Let me know if anything else weird crops up!
