### ISSUE TITLE
Mouse wheel input

### ISSUE THREAD

**Issue by grtlr** [plredmond/GPipe-GLFW#12]
I am currently looking at different options for implementing visualizations in OpenGL. I really like the idea of implementing most of the logic in Haskell using the ``GPipe`` package. Since the visualizations would require some user interaction, I was wondering if it is currently possible to grab input from the mouse wheel, or if such functionality is planned? I am afraid that I am too much of a beginner to create a pull request for this myself. What are your general plans for user input, is this something you want to investigate? Are there some resources, examples or tutorials to get started?

Thank you very much for all the work that went into making ``GPipe``!

**Comment by bch29** [comment]
You can do something like this using the `Unsafe` module (I haven't compiled it, so this is modulo minor type/syntax errors):

```haskell
import qualified Graphics.UI.GLFW as GLFW
import Graphics.GPipe.Context.GLFW.Unsafe

registerScrollCallback :: Maybe GLFW.ScrollCallback -> Context GLFWWindow os f m ()
registerScrollCallback callback = withContextWindow (\win -> setMouseButtonCallback (getGLFWWindow win) callback)
```

**Comment by plredmond** [comment]
@grtlr If you're interested to add this to the library and PR it, it shouldn't be too hard. If not, @bch29's suggestion works. :)

Either way, I'll add it as soon as i'm through with the job search I'm in the midst of!

**Comment by grtlr** [comment]
@bch29 Thank you very much for your answer!

@plredmond I will try to provide a PR. Would you be in favor of polling the mouse wheel position, or should I pursue a callback approach analog to @bch29's answer? If we choose the callback version, should we provide callbacks for other events (mouse position, keys, ...) too? Good look with your job search!

**Comment by plredmond** [comment]
@grtlr Thank for your effort, but remember that whether you PR is totally your decision. No stress. I'll do it eventually. If you choose to PR some code, the callback approach is more likely to get merged quickly. Don't feel as though you should add callbacks for all of the other things that GLFW supports. I'll add those eventually. :)

**Comment by plredmond** [comment]
Merged your pr & bumped patch version. I'll update the test program and hackage/stackage shortly.
