### ISSUE TITLE
removing unsafe interfaces

### ISSUE THREAD

**Issue by plredmond** [plredmond/GPipe-GLFW#14]
@bch29 @tobbebex @grtlr 
Hey all, (and anyone reading!)

It would be helpful if each of you would make a list the features of GLFW that you've used "unsafe" interfaces to access. Currently the unsafe interfaces are the `Unsafe` module and the window value provided to callbacks added via `registerScrollCallback`.

Given your input, I'll provide a type-safe encapsulation of those interfaces in the next major version. I'll make sure to ask for your feedback on preliminary implementations of those new abstractions.

Thank you,
PLR

**Comment by grtlr** [comment]
First of all, I am quite new to graphics programming and ``OpenGL``/``GLFW`` in general. With that said, I plan to use ``GPipe`` for visualizing and exploring datasets in 2D. To achieve this I need mouse inputs (which is possible now with scroll callbacks). I want to implement things like dragging the viewport and zooming to areas of the view. So everything that makes handling the mouse input more convinient would be very welcomed, but the basic functionality is there. I know this is a little bit offtopic, but might add to the discussion: I am still looking for a clever and idomatic way to implement dragging without to much ``IORefs`` and global state. How would you go about this?

**Comment by plredmond** [comment]
Hey, I'll contact you at your email to to discuss an approach which is lightweight and and could be added to this library.

**Comment by plredmond** [comment]
If everyone would indicate which GLFW features they've used 'unsafe' interfaces to access, I'll encapsulate them in a consistent safe interface.

**Comment by plredmond** [comment]
@grtlr Speaking to your concerns, I think using some combination of `IORefs`/`MVars`/`TVars` or a `StateT` are the normal way of dealing with state at a haskell program's top-level.

As for this issue: I've decided not to try to solve problems unrelated to simply exposing GLFW for GPipe. Further releases will expand the coverage of GLFW features and the next major release will remove the existing unsafe interfaces.
