### ISSUE TITLE
input encapsulation

### ISSUE THREAD

**Issue by plredmond** [plredmond/GPipe-GLFW#15]
Making an easy to use & idiomatic input library isn't necessarily straightforward, but there are lots of successful examples out there, so users of this library are welcome to provide their input. @grtlr has expressed a desire to support some abstractions on top of GLFW, such as a "dragging" interface.
## Current interfaces
- polling functions
  - `getCursorPos`
  - `getMouseButton`
  - `getKey`
- async/callback functions
  - `registerScrollCallback`
- raw unsafe GLFW interfaces
  - The unsafe module allows access to any GLFW inputs, but breaks the safety encapsulation of the library.

Examples and suggestions for improvements in 2.0 are welcome.

**Comment by plredmond** [comment]
In lieu of actually writiing a fully safe api, I've done a minimal wrapper around the suite of GLFW input interfaces. Suggestions are welcome, otherwise I'll release soon. https://github.com/plredmond/GPipe-GLFW/compare/more-inputs

**Comment by plredmond** [comment]
Released. Issues welcome.

**Comment by SwiftsNamesake** [comment]
Not sure if I should comment on a closed issue, but I think the ideal solution would be to expose a *safe* interface and let people implement whatever system they want on top of that.

**Comment by plredmond** [comment]
The system implemented in 1.4.x should be safe! :)
