### ISSUE TITLE
Make contextSwap call mainstep implicitly and remove mainloop

### ISSUE THREAD

**Issue by tobbebex** [plredmond/GPipe-GLFW#21]
I think this will be a cause for many user errors, and will add boilerplate to every GPipe example. Since you want to poll events at least as often as you draw that would be a good default. 

I still think its good to expose it if you expect rendering to be stalled for a long time or you want to react to events before rendering.

mainloop on the other hand wont really work in GPipe since you cant register a render callback in glfw that uses GPipe (you only have an IO there and no ContextT).

**Comment by plredmond** [comment]
> I think this will be a cause for many user errors, and will add boilerplate to every GPipe example.

Yes, I've forgotten to add `mainloop`/`mainstep` while creating my own examples and this has caused some confusion.

> Since you want to poll events at least as often as you draw that would be a good default.

Yes, I agree. That is how we processed events in previous versions. However, the [docs for GPipe's `contextSwap`](https://github.com/tobbebex/GPipe-Core/blob/64284984489f7be1408fd11f1d8cc7881a1a14e9/GPipe-Core/src/Graphics/GPipe/Internal/Context.hs#L72) should be changed to state that `contextSwap` is only ever called on the main thread. All of the GLFW calls which have the restriction of only being run on the main thread are executed by `mainstep`/`mainloop`.

Willfix!

---

> I still think its good to expose it if you expect rendering to be stalled for a long time or you want to react to events before rendering.

When GPipe supports a `forkIO` variant under `ContextT`. It will be important to allow control over exactly which thread performs the event processing done by `mainloop`/`mainstep`. If rendering is off the main thread, then `contextSwap` cannot be used for GLFW event processing.

> mainloop on the other hand wont really work in GPipe since you cant register a render callback in glfw that uses GPipe (you only have an IO there and no ContextT).

I'm not imaging the use-case of rendering in a callback. I was planning for support of multithreaded engines. Given a `forkIO` variant under `ContextT`, one could imagine a multithreaded program:
* main thread
   * Process events using `mainloop` OR
   * Process events using `mainstep` interlaced with required step-activities some other library which must be on the main thread.
* thread 2
   * Render loop written with GPipe.
* thread 3
   * Resource loading and buffer writing with GPipe.

**Comment by tobbebex** [comment]
Ah, I see. Then maybe hide it until withThread comes back?

**Comment by tobbebex** [comment]
Regarding the docs, you are perfectly right (it was already my intention, just poorly phrased)

**Comment by plredmond** [comment]
Ok this is done in 83c426bc2313e87c7d293f891757247dd52caf1c. I did a ton of random other refactoring and rewrote the docs. Check out `stack haddock` to see the new new.

**Comment by tobbebex** [comment]
Have updated the docs now
