### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by SwiftsNamesake** [plredmond/GPipe-GLFW#29]
There's currently a pull request implementing `getSize`, but I wonder if there's some reason that the cadre of window size/position functions haven't been wrapped yet?

If not, I'll submit a pull request when I have time.

**Comment by plredmond** [comment]
Could you add the names of the functions you'd like to see implemented to this issue?

My guess is that most of them belong to work in #25, which I've yet to do.

**Comment by SwiftsNamesake** [comment]
> Could you add the names of the functions you'd like to see implemented to this issue?

Certainly. I was mostly thinking of `getWindowSize` and the corresponding callback registering functions, along with an equivalent to GLFW's `setWindowPosCallback`.

I noticed afterwards however that `getWindowSize` is already covered by gpipe itself, although that one obviously relies on constant polling rather than a callback.

On a side note, does this library expose `pollEvents`?

**Comment by plredmond** [comment]
Those window functions will be added in work under #25. Currently GPipe exposes `getFrameBufferSize` backed by GLFW's function of the same name.

As for GLFW event processing, it is done [automatically when you call GPipe `swapBuffers`](https://www.stackage.org/haddock/lts-9.0/GPipe-GLFW-1.4.1/Graphics-GPipe-Context-GLFW-Window.html#g:2) and it is [configured via the HandleConfig](https://www.stackage.org/haddock/lts-9.0/GPipe-GLFW-1.4.1/Graphics-GPipe-Context-GLFW.html#t:ContextHandlerParameters).

**Comment by plredmond** [comment]
If you're interested to work on #25 in the same style as [Graphics.GPipe.Context.GLFW.Input](https://github.com/plredmond/GPipe-GLFW/blob/master/GPipe-GLFW/src/Graphics/GPipe/Context/GLFW/Input.hs), I'll happily accept a pull request! :)

**Comment by SwiftsNamesake** [comment]
I'll take a look.
