### ISSUE TITLE
Could callbacks run in a Context?

### ISSUE THREAD

**Issue by gilgamec** [plredmond/GPipe-GLFW#32]
It looks like input callbacks have to be in the IO monad, e.g. key callbacks are
```Key -> Int -> KeyState -> ModifierKeys -> IO ()```, mouse button callbacks are
```MouseButton -> MouseButtonState -> ModifierKeys -> IO ()```, and so on.
But in this case it's not clear to me how to get a callback to modify anything in a Context.
I could see doing something like
```haskell
GLFW.setKeyCallback win (Just $ \_ _ _ _ -> GLFW.setWindowShouldClose win True)
```
to close the window on any keypress, but it seems to be impossible in the current setup
as ```setWindowShouldClose``` is in a Context.

If there is indeed a way to do this, consider this Issue a request to add an example.

**Comment by plredmond** [comment]
The callback system is "supposed" to live in the ContextT transformer, but it can't because there's no facility in GPipe for me to wrap a normal IO action (eg. our callback action) in a ContextT. GPipe protects itself by not exposing such an interface.

**Comment by plredmond** [comment]
I recommend that you forward your callbacks via shared state (`MVars`) or communication (`Chan` & friends).
