### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by sorki** [plredmond/GPipe-GLFW#4]
The application I've built recently is like hybrid CLI/GUI thingie and its output gets interleaved with debug messages.

Would you accept a PR changing `debug` function to `debug = const $ return ()` while retaining the old one as e.g. `debug'` so it can be switched if needed?

Btw thanks for `setWindowSizeCallback`, I've added it and noticed it's already there during rebase!

**Comment by plredmond** [comment]
The reason why I never got around to this change is because some of the logging is important for debugging rare crashes because it represents error conditions, and some of the logging is just noise. I'd like to add a flag to reduce the noise, but deciding which of the debugs are indeed noise is a little hard.

Can you please paste the output which you'd like suppressed into this ticket and I'll put those behind a flag?

**Comment by plredmond** [comment]
Alternatively, I could thread a log function through everything and let the user provide a handler `Maybe (String -> IO ())`. That might be cleaner (it leaves behind no "always on" log messages) but it might hide error conditions.

**Comment by plredmond** [comment]
Or maybe having log levels would be the best of both worlds..?

**Comment by plredmond** [comment]
```
[NaNs, ThreadId 11 has Nothing]: contextHandlerCreate
[0.145s, ThreadId 11 has Nothing]: made context Just (Window {unWindow = 0x00000000008add60}) -> parent Nothing
[0.220s, ThreadId 11 has Nothing]: made context Just (Window {unWindow = 0x0000000000bb1dc0}) -> parent Just (Window {unWindow = 0x00000000008add60})
[0.221s, ThreadId 11 has Nothing]: attaching Just (Window {unWindow = 0x0000000000bb1dc0}), reason: contextDoAsync required a specific context
[1.192s, ThreadId 11 has Just (Window {unWindow = 0x0000000000bb1dc0})]: contextDelete of Just (Window {unWindow = 0x0000000000bb1dc0})
[1.196s, ThreadId 11 has Nothing]: contextHandlerDelete
```
I guess all of this output is noise. That means I'd silence these messages (or if using log-levels, I'd make them `DEBUG` level):
* `contextHandlerCreate`
* `made context %s -> parent %s`
* `attaching %s, reason: %s`
* `contextDelete of %s`
* `contextHandlerDelete`

Are there additional messages that you've seen that you think ought to be silence-able?

**Comment by plredmond** [comment]
I added a logger and marked most messages as `DEBUG` or `INFO`: https://github.com/plredmond/GPipe-GLFW/blob/master/GPipe-GLFW/CHANGELOG.md#200----unreleased

Try out the current HEAD and let me know if it works for you.

**Comment by sorki** [comment]
Thank you! Tried with HEAD and it's looking good. Will post a link and close this when I'm done with finishing touches so you can try as well :)

**Comment by sorki** [comment]
The app https://github.com/sorki/implicitpipe

Thanks for the lib and fixes!

**Comment by plredmond** [comment]
> While the application is running you can open the source file in your editor and it will automatically reload the preview on saves.

Woahh, this is really cool!
