### ISSUE TITLE
Shared contexts shouldnt be multithreaded

### ISSUE THREAD

**Issue by tobbebex** [plredmond/GPipe-GLFW#5]
First off, using runSharedContextT results in a crash with GPipe-GLFW on windows.

The reason for this is stated under "Remarks" on this page
http://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344:
*"Windows: The context to share resources with may not be current on any other thread."*

This crash is however symptomatic for a more profound issue:
**Shared contexts shouldnt be multithreaded.**

Instead, two (or more) shared contexts should reuse the same command thread, augmenting each message with which window to make current (or, in the case of creating a shared context, make uncurrent).

Besides making it easy to fix the crash for creating shared contexts, this will:
* Remove race conditions that appear in the current design, eg where a texture may be rendered by one context and then sampled by a second. The wrappings of ContextT monads makes this order dependent, but that is lost when the commands are sent to two different threads.
* Improve performance even when there aren't any race conditions. I have in previous work seen that issuing commands to shared contexts from multiple threads will cause blocking internally in the drivers, making the multi threaded code perform even worse than single threaded code.

**Comment by tobbebex** [comment]
Fixed by self in aadcf241ae16e416315655ed2aa1e0b7989ae301

**Comment by plredmond** [comment]
So, I noticed that this fix peppers calls to `GLFW.makeContextCurrent` around.. Should this be a concern, since moving the context (I think) clears the buffers?

**Comment by tobbebex** [comment]
It isn't avtually moving the context but (potentially) switching between contexts on the same thread. Even so, it wouldn't clear the buffers, but it might cause some overhead. I think the redundant case (switching to the already active window) is cheap though.

I did test it with two shared contexts and it works as expected.
