### ISSUE TITLE
Expose `HandleConfig` `configLogger`?

### ISSUE THREAD

**Issue by mrehayden1** [plredmond/GPipe-GLFW#7]
Shouldn't this field be exposed so users can switch off logging?

**Comment by plredmond** [comment]
Perhaps! I'm not sure. This project is in dire need of an overhaul, but I don't have the time to do it.

**Comment by mrehayden1** [comment]
Would you accept a patch?

It seems like the feature author didn't know that HandleConfig uses an explicit export list.

**Comment by plredmond** [comment]
Sure, go ahead! I'll put it on hackage after merging and bumping the version.
