### ISSUE TITLE
Finalizers doesn't work correctly with shared contexts

### ISSUE THREAD

**Issue by tobbebex** [plredmond/GPipe-GLFW#7]
Finalizers for shared objects like textures should still be run after context is destroyed if it had shared contexts, but in one of those contexts. Finalizers for non-shared objects like VBAs and FBOS must not be run after context is destroyed.

Depends on tobbebex/GPipe-Core#10.

**Comment by tobbebex** [comment]
Fixed in c43de60213afaa9d087bd21d398585671537ae99. Unfortunately required a major version bump.

**Comment by tobbebex** [comment]
@plredmond , we need to synchronize the release of our packages to Hackage since we have major version bumps. Let me know when you're back and we'll give it a go

**Comment by plredmond** [comment]
I can't build on the little computer I've brought with me. Would it be
alright to delay release until sept 22?

**Comment by tobbebex** [comment]
Sure, no problem!


> 17 sep 2015 kl. 07:48 skrev PLR <notifications@github.com>:
> 
> I can't build on the little computer I've brought with me. Would it be
> alright to delay release until sept 22?
